run:
  issues-exit-code: 1
  tests: true

linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - golint
    - gocyclo
    - gofmt
    - misspell
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
  fast: true
