version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  stage:
    docker:
      - image: circleci/golang:1.12
    working_directory: ~/bishack.dev
    environment:
      TEST_DIR: /tmp/tests
    steps:
      - checkout
      - run: mkdir -p $TEST_DIR
      - restore_cache:
          keys:
            - v1-pkg-cache
      - run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $$(go env GOPATH)/bin v1.24.0
      - run: curl -sf https://up.apex.sh/install | sudo sh && go mod download
      - run: make deploy
      - run: mv coverage.txt /tmp/tests/coverage.txt
      - codecov/upload:
          file: /tmp/tests/coverage.txt
      - store_artifacts:
          path: /tmp/tests
          destination: out
      - store_test_results:
          path: /tmp/tests
  prod:
    docker:
      - image: circleci/golang:1.12
    working_directory: ~/bishack.dev
    environment:
      TEST_DIR: /tmp/tests
    steps:
      - checkout
      - run: mkdir -p $TEST_DIR
      - restore_cache:
          keys:
            - v1-pkg-cache
      - run: go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
      - run: curl -sf https://up.apex.sh/install | sudo sh && go mod download
      - run: make deploy.prod
      - run: mv coverage.txt /tmp/tests/coverage.txt
      - codecov/upload:
          file: /tmp/tests/coverage.txt
      - store_artifacts:
          path: /tmp/tests
          destination: out
      - store_test_results:
          path: /tmp/tests
workflows:
  version: 2.1
  build-deploy:
    jobs:
      - stage:
          filters:
            branches:
              only: master
      - prod:
          filters:
            branches:
              only: production
