version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: ~/bishack.dev
    environment:
      TEST_DIR: /tmp/tests
    steps:
      - checkout
      - run: mdkir -p $TEST_DIR

      - restore_cache:
          keys:
            - v1-pkg-cache

      - run: curl -sf https://up.apex.sh/install | sh && go mod download

      - run: make test

      - store_artifacts:
          path: /tmp/tests
          destination: out
      - store_test_results:
          path: /tmp/tests
